### ISSUE TITLE
Custom provider: Existing ID4 hosted server

### ISSUE THREAD

**Issue by ax2000** [verbb/social-login#1]
### Question

Hi @engram-design & co,

I’ve got a client that has a custom [Identity Server 4](https://github.com/IdentityServer/IdentityServer4) with Auth0 in place that handles autorisations with other existing systems and we are trying to workout what would be the best option to integrate that with a new craft project. 

We've tried using the Auth0 provider, but it assumes that the authentication url is handled via auth0.com, which is fair. 

The flow we’ve got in mind would be something like:
1. When trying to login, redirect to the custom ID4 server to handle authentication
2. On success, redirect back to Craft's CP Dashboard

Do you think we could leverage the Social Login plugin and create a Custom Provider that extends the current Auth0 provider? Or maybe we should be extending your [auth module](https://github.com/verbb/auth)?

Apologies if this is described in the docs, I’m more of a frontend dev so not sure what will be the best path to achieve this, any pointers will be greatly appreciated.

If you need me to provide more context, please let me know.

Thanks heaps,
Alby

**Comment by engram-design** [comment]
A custom provider that extends the Auth0 is an excellent idea. But I've also added the ability to set a custom domain on the Auth0 provider, if that'll work for you!

To get this early, run `composer require verbb/social-login:"dev-craft-4 as 1.0.0"`

**Comment by ax2000** [comment]
Great - thanks heaps for this @engram-design!

We are testing it and will let you know.

**Comment by engram-design** [comment]
Updated in [1.0.1](https://github.com/verbb/social-login/releases/tag/1.0.1)
