### ISSUE TITLE
Error with Google Login in 1.0.5 

### ISSUE THREAD

**Issue by tomkiss** [verbb/social-login#11]
### Describe the bug

I upgraded to 1.0.5 and it immediately broke signin using Google auth. Downgrading resolved the issue.

I don't have any other auths setup apart from Google.

### Steps to reproduce

I received the sign-in button for Google (using the standard template code), but after clicking it, was kicked back to the login page with sign-in error. This also occurred on the CP login.

In the logs, I can see:
`[error] social-login: Unable to authorize login for “google”: “Calling unknown method: verbb\sociallogin\providers\Google::getDefaultScopes()” /var/www/html/vendor/yiisoft/yii2/base/Component.php:300`

### Craft CMS version

4.4.15

### Plugin version

1.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [1.0.6](https://github.com/verbb/social-login/releases/tag/1.0.6)

**Comment by tomkiss** [comment]
Appears to be working! Thanks 😊
