### ISSUE TITLE
CPLogin enabled currentUser return null with a normal login

### ISSUE THREAD

**Issue by franck-thorck** [verbb/social-login#16]
### Describe the bug

When I install the Social Login plugin and enable CpLogin, I have a Twig error saying that the currentUser is null.

### Steps to reproduce

1. Install the last version of the plugin
2. Enable cpLogin from project.yml or social-login.php
3. Login with a normal email / password credentials

### Craft CMS version

4.6.0

### Plugin version

1.0.9

### Multi-site?

Yes

### Additional context

<img width="1393" alt="Capture d’écran, le 2024-01-13 à 09 08 40" src="https://github.com/verbb/social-login/assets/117709151/b14afb08-d3c8-493a-9ea6-c5ff4a625e12">

**Comment by engram-design** [comment]
I can't reproduce this one, sorry. That's a Craft template as well, and I'm not sure how it's possible that `currentUser` isn't an available variable.

Is there any more context for that stack trace, further down the page? As in, where it's being called from?

Does this page show immediately after you login? Would there be any other plugins that are messing with behaviour?

Lastly, are there any logs in your `/storage/logs` folder for `social-login` or `auth` ?

**Comment by franck-thorck** [comment]
Here a video: https://www.loom.com/share/600e81310f3343989146b0e106568712?sid=4761f5cf-5211-4250-8b90-b37037bfb824

After the video record, I changed the handle of userGroup in the configuration file for uuid, but no changes.

I check in the different log files: `web.log`, `phperrors.log` and `social-login.log` but nothing about an error stack. And I don't have the `auth.log` file.

**Comment by engram-design** [comment]
What I meant about the error - the screenshot you provided shows the last snippet of the error, it'd be great to see it in its entirety, so I can trace back where the error is being triggered form.

You're welcome to send your error logs to `support@verbb.io` and I can take a look.

And, in addition - if you're able to send your database and `composer.json`, and `composer.lock` file through to the above email, that'd help a lot. Of course, I understand if you're not able to share your database, but just thought it'd be a good way to replicate the error you're getting, as at a glance, I'm not sure how that's possible.

**Comment by franck-thorck** [comment]
All done I sent an email with all the information needed.

**Comment by engram-design** [comment]
Thanks for that, will take a look shortly...

**Comment by franck-thorck** [comment]
It was due to a custom module.

Everything works now, thank you for the time !
