### ISSUE TITLE
Unable to register new user

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/social-login#2]
### Describe the bug

We have a website where we want to use Auth0 to login both control panel as front-end users, we used to do it with another plugin, but that one isn't maintained anymore, so therefore we want to make the switch to this one.

<img width="459" alt="Screenshot 2023-03-31 at 18 18 57" src="https://user-images.githubusercontent.com/6649706/229175429-d6affb4e-eba9-4d4d-9d9c-6499c341d32d.png">

We've inserted all the credentials in Craft, mapped the email and added the callback on Auth0, but when the user uses the Auth0 login button on the admin panel, we keep getting following error:

```
2023-03-31 18:09:53 [ERROR] Unable to register new user.
2023-03-31 18:09:53 [INFO] Request context:
$_GET = [
    'p' => 'social-login/auth/callback'
    'code' => 'Ph6iXhHUG8Leni65wtO4VOoC6u<shortened-to-obsure>HjJwOZSmgGDk1TB4S7S'
    'state' => '072cb51fae0246b6c1cb357ee03b78f9'
]
```

When the same user (on our test environment) does so with the other plugin, the account is created succesfully. Are we forgetting something or is something wrong? Thanks in advance!

### Steps to reproduce

1. Add Auth0 as a social provider
2. Try to login/register via the Auth0 button on the admin login panel

### Craft CMS version

4.4.5

### Plugin version

1.0.0

### Multi-site?

Yes

**Comment by ishetnogferre** [comment]
Okay, nvm, it's actually explained in the docs:
https://verbb.io/craft-plugins/social-login/docs/feature-tour/registration#control-panel-registration

**Comment by engram-design** [comment]
Yup, so registration via the control panel would be a security risk. All it would take is for me to find your control panel login page, login with my social media account, and bam - I've got access to your site. 

Even if we were to allow registration, and it assigned them to your default user group, they wouldn't (typically) have access to the control panel. So it doesn't make sense to have them able to login to the control panel if they aren't able to.

Not sure why the docs cut off at that point, but just updated that with a better description.
