### ISSUE TITLE
Identity Server 4 requires different auth0 getBaseAccessTokenUrl

### ISSUE THREAD

**Issue by ax2000** [verbb/social-login#21]
### Question

Hi there,

This question is both related with Social Login and the Auth module.

We connect to ID4 using the Auth0 Social Login provider. Everything works well except that we need to modify the `getBaseAccessTokenUrl` in the auth0 provider module in order to work.

It seems that the ID4 get token endpoint is `{baseUrl}/token` whilst auth0's endpoint is `{baseUrl}/oauth/token`.

We have changed the auth0 module `getBaseAccessTokenUrl` as per below and it all works correctly, but it's not a real fix for it, just a confirmation that we need a different url for ID4.

```
public function getBaseAccessTokenUrl(array $params = [])
    {
        //return $this->baseUrl() . '/oauth/token';
        return $this->baseUrl() . '/token';
    }
```

I'm not sure what would be the best way to achieve the above. Should we create a custom Social Login provider and a custom Auth provider? Or can we extend somehow the current Social Login Auth0 provider so it has a different Get Token url?

Please let me know if the above makes sense or if you'd need me to provide more info. Any help would be greatly appreciated.

Cheers,
Alby

**Comment by engram-design** [comment]
I'm not familiar with ID4, is that a separate service/provider or part of Auth0? It might warrant its own provider if it's a widely known one, or if it's specific to your use case, maybe we need to add the ability to change the `baseUrl` for a provider.

We can very easily create a new provider in Auth that extends Auth0, I just wanted to clarify what that was first.

**Comment by ax2000** [comment]
Thanks Josh.

I'm not super familiar with ID4 either. Our client has other systems in place working on .NET and that's what they use for SSO between all systems.

From what I can see, the current Auth0 provider works perfectly except for the endpoint they use for a token request. [ID4 docs](https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html#requesting-an-access-token-using-a-refresh-token) mention `/token` whilst [Auth0 docs ](https://auth0.com/docs/api/authentication#authenticate-user)use `/oauth/token`.

I think having the ability to change the `baseUrl` within the provider will do the job but I'm happy to go whichever way you think will be best.

**Comment by engram-design** [comment]
Just added that in [1.0.10](https://github.com/verbb/social-login/releases/tag/1.0.10) as a new provider.

I wasn't sure if you need the Region, Domain, etc that Auth0 does, but I've included that anyway.

**Comment by ax2000** [comment]
Thanks heaps for putting that together so promptly.

I installed the update but I'm getting the following error in the logs

```
2024-03-23 16:17:52 [ERROR] Unable to authorize login for “identityServer4”: “Class "verbb\auth\clients\auth0\provider\IdentityServer4" not found” /var/www/html/vendor/verbb/auth/src/providers/IdentityServer4.php:7
2024-03-23 16:17:52 [INFO] Request context:
$_GET = []

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'social-login/auth/login'
    'loginName' => ''
    'provider' => 'identityServer4'
]
```

I checked a couple of times and the new ID4 provider has the same settings as the old Auth0. Auth0 seems to still work ok but getting the above error with the ID4 provider, not sure if I'm missing something though.

**Comment by engram-design** [comment]
Ah, sorry about that. You'll need to update the `verbb/auth` module to the latest. Best to run `composer update` to get that updated.

**Comment by ax2000** [comment]
Thanks for checking that - Unfortunately I still keep getting the error below after running `composer update`. I also cleared caches just in case.

```
$_POST = []
2024-03-24 11:28:10 [ERROR] Unable to authorize login for “identityServer4”: “Class "verbb\auth\clients\auth0\provider\IdentityServer4" not found” /var/www/html/vendor/verbb/auth/src/providers/IdentityServer4.php:7
2024-03-24 11:28:10 [INFO] Request context:
$_GET = []

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'social-login/auth/login'
    'loginName' => ''
    'provider' => 'identityServer4'
]
```

Using the `auth0` provider instead of the `identityServer4` seems to work though.

Not sure if it's related to my environment. In case it helps these are the versions I've got installed:
- Craft Pro `4.8.5`
- Social Login `1.0.10` 

I'll try a fresh install asap to see if it also happens there and will let you know.

**Comment by engram-design** [comment]
For some reason, looks like my changes didn't get pushed through for the new version of [auth](https://github.com/verbb/auth/releases/tag/1.0.19). Would you be able to try a `composer update` again?

**Comment by ax2000** [comment]
Yep that did the trick - working beautifully now.

Thanks heaps Josh!
