### ISSUE TITLE
Salesforce getBaseApiUrl method missing Token parameter

### ISSUE THREAD

**Issue by jacksutherland** [verbb/social-login#27]
### Describe the bug

Installing the latest version of the plugin and going to the Providers tab immediately throws the following error:
_**Declaration of verbb\sociallogin\providers\Salesforce::getBaseApiUrl(): ?string must be compatible with verbb\sociallogin\base\OAuthProvider::getBaseApiUrl(?verbb\auth\models\Token $token): ?string**_

### Steps to reproduce

1. Install the latest version of the plugin on the Craft 5.1.2
2. Go to the plugin's settings
3. Click on the providers tab

### Craft CMS version

5.1.2

### Plugin version

2.0.0 (tria)

### Multi-site?

No

### Additional context

The Salesforce getBaseApiUrl method appears to be missing a Token parameter. Adding the code below to `src/providers/Salesforce.php` clears the error. 

**Change this:**
```
public function getBaseApiUrl(): ?string
{
        $url = $this->getApiDomain();

        return "$url/services/data/v49.0";
}
```

**To this:**
```
use verbb\auth\models\Token;

public function getBaseApiUrl(?Token $token): ?string
{
        $url = $this->getApiDomain();

        return "$url/services/data/v49.0";
}
```

I have not tested this using Salesforce.

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/social-login/releases/tag/2.0.1)
