### ISSUE TITLE
Userprofile id is empty

### ISSUE THREAD

**Issue by RobinWithouck** [verbb/social-login#3]
### Describe the bug

We use Auth0 as provider. When the users tries to login we can read this in the logfile:

```
2023-04-06 16:17:04 [ERROR] Unable to process callback for “auth0”: “SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'identifier' cannot be null
The SQL being executed was: INSERT INTO `social_login_connections` (`userId`, `providerHandle`, `identifier`, `dateCreated`, `dateUpdated`, `uid`) VALUES (46367, 'auth0', NULL, '2023-04-06 14:17:04', '2023-04-06 14:17:04', '7892d63c-f089-465e-9b3c-ce5c01ba314a')” /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
2023-04-06 16:17:04 [INFO] Request context:
$_GET = [
    'p' => 'social-login/auth/callback'
    'code' => 'wxpG2QLwFwJg2X3RguHt0Mno7ezmmgk12orGTJ_ifpXZi'
    'state' => 'bf66ca5b61b8c2742d887078dca1b344'
]
```

When we tried to debug this issue, we noticed this is empty when the profile is generated in this part of code on line 40:

![Screenshot 2023-04-06 at 16 29 54](https://user-images.githubusercontent.com/6160509/230408861-77421d55-525b-4793-b054-721876a86edf.png)

This is the template code we used for testing. The same thing happens when we use the button implementation.

```
<form method="POST">
	{{ csrfInput() }}
	{{ actionInput('social-login/auth/login') }}
	{{ hiddenInput('provider', 'auth0') }}
	{{ redirectInput('/my-account') }}
	<button type="submit">Login met AUTH0</button>
</form>
```

We were able to register a user with the same Auth0 settings. 

Is this something that is missing from Auth0?

### Steps to reproduce

1. Setup the Auth0 provider
2. Use the example code in the template
3. Click the button

### Craft CMS version

4.4.5

### Plugin version

1.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Updated in [1.0.1](https://github.com/verbb/social-login/releases/tag/1.0.1)
