### ISSUE TITLE
Redirect no longer honoured

### ISSUE THREAD

**Issue by StuartMcD** [verbb/social-login#34]
### Describe the bug

After recent point updates the redirect function is no longer being honoured, it still creartes a user, send the email but they are returned to the original URL irrsepective;

`{{ craft.socialLogin.getLoginUrl('google',{ redirect: siteUrl }) }}`

`{{ craft.socialLogin.getLoginUrl('google',{ redirect: '/' }) }}`

### Steps to reproduce

1. CMS: User confirmation required
2. Click link as above (google in testing)
3. Sign-in all good
4. Return to the same URL 
5. User created as Pending
6. Email delivered

### Craft CMS version

4.9.7

### Plugin version

dev-craft-4 as 1.0.15

### Multi-site?

No

**Comment by engram-design** [comment]
You've always needed to [hash the redirect](https://verbb.io/craft-plugins/social-login/docs/feature-tour/login#redirection) to prevent tampering with, and that's working for me?

```
{{ craft.socialLogin.getLoginUrl('google', { redirect: ('https://verbb.io' | hash) }) }}
```

**Comment by StuartMcD** [comment]
I saw that in the docs but it didn't tweak it was required, thx.
