### ISSUE TITLE
Possible Craft Commerce related issue

### ISSUE THREAD

**Issue by ax2000** [verbb/social-login#35]
### Describe the bug

Hi there,

This issue is related to [this one in Craft Commerce](https://github.com/craftcms/commerce/issues/3533).

Just wondering if there's a rough ETA for a possible fix?

Thanks heaps,
Alby

### Steps to reproduce

As per https://github.com/craftcms/commerce/issues/3533

### Craft CMS version

Craft Pro 4.9.7

### Plugin version

1.0.15

### Multi-site?

No 

### Additional context

Craft Commerce 4.6.2

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/social-login:"dev-craft-4 as 1.0.15"`. Should have a release out this week.

**Comment by ax2000** [comment]
Great - thanks heaps for this @engram-design - I've tested and can confirm it all works as expected now.
