### ISSUE TITLE
Call to protected method getDefaultScopes() when using custom scopes via config

### ISSUE THREAD

**Issue by gilleard** [verbb/social-login#4]
### Describe the bug

The _if custom scopes_ check at src/base/OAuthProvider.php:64 seems to then call a protected method?

May be more related to the base auth packages though...

### Steps to reproduce

1. Add any value to the scopes of the provider you're going to use in the plugin's config file, such as:

`'providers' => [
    'google' => [
        'scopes' => [
            // TODO: adding her breaks, due to getDefaultScopes call
            'https://www.googleapis.com/auth/business.manage',
        ],
    ],
],`

2. Attempt to sign in using said provider
3. Check the log file:

`2023-04-11 10:17:06 [ERROR] Unable to authorize login for “google”: “Call to protected method verbb\auth\clients\google\provider\Google::getDefaultScopes() from scope verbb\sociallogin\base\OAuthProvider” /var/www/vendor/verbb/social-login/src/base/OAuthProvider.php:65`

### Craft CMS version

4.4.6.1

### Plugin version

1.0.0

**Comment by engram-design** [comment]
Should be fixed in [Social Login 1.0.2](https://github.com/verbb/social-login/releases/tag/1.0.2) and [Auth 1.0.4](https://github.com/verbb/auth/releases/tag/1.0.4)
