### ISSUE TITLE
Incomplete settings form for Amazon Cognito Provider

### ISSUE THREAD

**Issue by lucbernard** [verbb/social-login#41]
### Describe the bug

Seems like the Amazon Cognito might be missing some fields?

Looking at auth's Amazon Cognito client, the [constructor function expects](https://github.com/verbb/auth/blob/craft-5/src/clients/amazoncognito/provider/AmazonCognito.php#L46) to receive either a hostedDomain or a cognitoDomain/region couple.

I couldn't find a place to enter those values in Craft's Social Login form for Cognito. Looking at the template, the form only seems to include de base `providers/_oauth` template.

### Steps to reproduce

1. In the admin, go to Social Login settings, Providers section
2. Click on `Amazon Cognito`
3. Form only allows to enter `clientId` & `clientSecret`. No way to enter the  `hostedDomain` or `cognitoDomain/region` options

Attempting to use the AWS Cognito SSO will raise a `Neither "cognitoDomain" and "region" nor "hostedDomain" options are set. Please set one of them` exception.

<img width="1268" alt="Screenshot 2024-07-16 at 13 13 12" src="https://github.com/user-attachments/assets/7c903713-2fdc-4cdf-a986-faffd6409eb6">

### Craft CMS version

5.2.6

### Plugin version

2.0.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [2.0.4](https://github.com/verbb/social-login/releases/tag/2.0.4) with the addition of a "Domain" setting. I've also added [docs](https://verbb.io/craft-plugins/social-login/docs/providers/all-providers#amazon-cognito) for setup.
