### ISSUE TITLE
Creating account via Social and an account with the same email exists, wipes all the data for the account

### ISSUE THREAD

**Issue by jamesevans1808** [verbb/social-login#42]
### Describe the bug

if you sign up using email based login via Craft, then you login via social login, if the email you used was the same then the original email based account gets wiped (user groups reset, profile changes)

### Steps to reproduce

1. Create an account through Craft with an email address.
2. Change some details/add a group 
3.  Login using a social provider that has an account under the same email address
4. Note how any changes to the account are gone. 

### Craft CMS version

5.2.3

### Plugin version

2.0.3

### Multi-site?

No

### Additional context

I noticed the "Connecting" service in the documentation, but this appears to be a more manual process for someone that is already logged in with their account and wishes to then connect it to a social media account. Is there a way of doing a check on Login via social to look for accounts under that email and then prompt connections?

Thanks

**Comment by engram-design** [comment]
The only way that should be possible is if the `syncProfile` setting was enabled. This is going to update your account every time you login. Refer to the PRs for this https://github.com/verbb/social-login/pull/29 and https://github.com/verbb/social-login/pull/40

Does disabling this setting make a difference?

**Comment by jamesevans1808** [comment]
Ah yes, thats probably why. I'd missed that, sorry! Will it still sync details on account creation when using social-login?

**Comment by engram-design** [comment]
I've just realised that's on by default, and I don't like that as behaviour from a PR - I should've caught that. It'll now be disabled by default.

And yep, if the user is created for the first time (when they first sign in with Social Login and a User element is created), their profile will be populated if the `populateProfile` setting is enabled. Subsequent logins will not touch the User element.

**Comment by jamesevans1808** [comment]
Awesome, thanks for the help there!
