### ISSUE TITLE
Add a Twig shortcut to check whether Social Login is enabled on the front-end.

### ISSUE THREAD

**Issue by jdsdev** [verbb/social-login#43]
### What are you trying to do?

I want social login links to stop showing when `enableLogin` is false. This is already handled automatically when `enableCpLogin` is false. I can accomplish this by loading the plugin settings in Twig and checking `enableLogin`, which isn't overly complicated, but feels convoluted for what seems like it should be basic functionality.

### What's your proposed solution?

Add a variable to check whether `enableLogin` is true or false, and include the check in the sample login template code.

**Comment by engram-design** [comment]
Happy to add a shortcut for it, but you can also access it through the `craft.socialLogin.plugin` variable, which represents the instance of the Social Login plugin to access all sorts of things.

```twig
{{ craft.socialLogin.plugin.settings.enableLogin }}
```

**Comment by jdsdev** [comment]
Thanks for the reply, that is essentially what I'm doing, and it does work. When I first disabled login, it felt like hiding the login buttons should be the default behavior, and I posted the feature request, but I understand that it will always require a Twig variable, so it's just a question of whether it's a short one or a longer one.
