### ISSUE TITLE
Can't create user due foreign key constraint violation

### ISSUE THREAD

**Issue by ishetnogferre** [verbb/social-login#5]
### Describe the bug

We have a Auth0 connection setup and had some users already registered before installing the plugin. 
When connecting the users via Auth0, some work and some don't. For those that don't work, we get following error:

```
Unable to process callback for “auth0”: “SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ID271560_coshacc`.`social_login_connections`, CONSTRAINT `fk_gcaulyeznerwbfonaeaxbrllddhqmxjqolno` FOREIGN KEY (`id`) REFERENCES `elements` (`id`) ON DELETE CASCADE)

The SQL being executed was: INSERT INTO `social_login_connections` (`userId`, `providerHandle`, `identifier`, `dateCreated`, `dateUpdated`, `uid`) VALUES (90370, 'auth0', 'google-oauth2|107157376775655885595', '2023-04-24 09:48:10', '2023-04-24 09:48:10', 'ba5328d5-4c8b-456c-b2ed-c563bf40c419')” /data/sites/web/cosheco4556/web/acc.cosh.eco/vendor/yiisoft/yii2/db/Schema.php:676
2023-04-24 11:48:10 [INFO] Request context:
$_GET = [
    'p' => 'en/social-login/auth/callback'
    'code' => 'BaHgFALrogfwb-cvFDtJ7dIRX7yKdMKvEsF6fPd6GV6HK'
    'state' => 'e52a4f60137e3486c306efe1d2da4b1d'
]
```

I myself don't know that much about how mySQL works in detail, so everything below might not be connected to the issue but I'll just take your through my digging through the database and what I found: 

First I made sure that foreign key existed in the database by looking at the relationships view
<img width="1466" alt="Screenshot 2023-04-24 at 14 31 44" src="https://user-images.githubusercontent.com/6649706/233999221-8a3ca761-e22e-48b5-96ec-641870d45489.png">

So constraint `fk_gcaulyeznerwbfonaeaxbrllddhqmxjqolno` is the one about the `elements` table, which I found weird, cause the `id` in the `social_login_connections` looked like a independent id to me and the only relationship needed would be the `userId` with the `id` in the users table. So i went looking at those two tables.

The `social_login_connections` table currently does have an id which links to the elements table
<img width="518" alt="Screenshot 2023-04-24 at 14 31 29" src="https://user-images.githubusercontent.com/6649706/233999983-cfade932-384e-464a-b6a2-2028edc3d8aa.png">

So i clicked on them to see what they would match in the `elements` table:
![Screenshot 2023-04-24 at 14 32 02](https://user-images.githubusercontent.com/6649706/234000213-54469362-e325-4a8a-90b8-88079323539c.png)

And the first one is correct, cause the admin user was the first element made, but the others are linking to wrong elements (GlobalSet, Entry, Block, ...). Oddly enough the ids of the `social_login_connections` are exactly the same order and number as these ids.

Now this is just a guess, as I don't understand the mechanics of mySQL up till that point, but I think we get a successful connected user for every time the incrementing id of `social_login_connections` matches an id in the `elements`table?

I hope the information provided can somewhat help resolve this issue, do let me know if you need anything other or if we need to test/change things in our code.

Thanks in advance!

### Steps to reproduce

1. Make `elements` have a non subsequent list of ids (e.g. 1 2 3 5 9 ...)
2. Add 4 users and see if the fourth user is successfully added

### Craft CMS version

4.4.7.1

### Plugin version

1.0.2

### Multi-site?

yes

**Comment by engram-design** [comment]
Yep, totally an error on my part, that foreign key should've never been in there! Connections aren't elements.

Should be fixed in [1.0.3](https://github.com/verbb/social-login/releases/tag/1.0.3)
