### ISSUE TITLE
Login with Azure account

### ISSUE THREAD

**Issue by kristofser** [verbb/social-login#6]
### Question

Is there a reason why it's not possible to login with an Azure account (since you can also login with an existing Microsoft account)

As far as I can see you got the right code for authentication implemented. (except for tenant id that is now hard coded on common instead of configurable id).

The reason I ask is because being able to work with the Azure portal makes it more interesting for our clients that have set up their own Azure services, to login and manage the clients they want to grant access to log into their Craft backend.

**Comment by engram-design** [comment]
So the last time I looked at this, we don't actually get any profile data from Azure, which is the prerequisite for using it as a login provider for Social Login. We need something to record against a user to associate them with a login. This would be the [resource owner](https://github.com/TheNetworg/oauth2-azure#resource-owner) which is supported. Changing the `tenant` is also very doable.

I may just need to give it another look! I'm not exactly an expert on Azure I'm afraid.

**Comment by kristofser** [comment]
Hey @engram-design Thx!

I've already written this in a custom framework, so normally it's very doable with the code that is already present (which is very cleanly written).

Maybe I'll give it a try in the next few days and open a pull request for it.
Crafcms is not my main framework to work in, so we'll see how that goes :-D
