### ISSUE TITLE
Allow multi-site callback support

### ISSUE THREAD

**Issue by daniel-league-agency** [verbb/social-login#9]
### What are you trying to do?

I’m trying to use the `social-login` plugin to authenticate the users of a multi-site

The callback request needs to go through the site it was created from in order to assign the session cookie for the user to that specific site.

Although locally we are using subdomains of localhost, in production the multi-sites are split across multiple top level domains so we can’t use `defaultCookieDomain` in the project config to share the cookie between multisites.

### What's your proposed solution?

Relevant code snippet from `OAuthProvider.php`
```php
public function getRedirectUri(): ?string
{
    $siteId = Craft::$app->getSites()->getPrimarySite()->id;

    // We should always use the primary site for the redirect
    return UrlHelper::siteUrl('social-login/auth/callback', null, null, $siteId);
}
```

Change functionality of `getRedirectUri` in `OAuthProvider.php` to obtain the `$siteId` from `Craft::$app->getSites()->currentSite->id;` instead of `Craft::$app->getSites()->getPrimarySite()->id;` so the callback goes to the relevant site the login/auth url was routed from.

I have tested this locally with the Google provider by editing the vendor files to confirm it works as expected.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/social-login:"dev-craft-4 as 1.0.3"`.

**Comment by engram-design** [comment]
Updated in [1.0.4](https://github.com/verbb/social-login/releases/tag/1.0.4)
